export const afirmaciones = [
    "Soy una mujer fuerte y capaz de superar cualquier desafío 💪✨",
    "Mi experiencia de vida me hace más sabia cada día 🌟",
    "Acepto y amo cada etapa de mi vida con gratitud 🙏💖",
    "Mi edad es mi mayor tesoro, llena de aprendizajes y momentos valiosos 📚✨",
    "Encuentro paz en el presente y esperanza en el futuro 🕊️💫",
    "Soy merecedora de amor, respeto y abundancia 👑💝",
    "Mi voz interior es sabia y me guía por el camino correcto 🎯💫",
    "Cada día es una nueva oportunidad para brillar ⭐️✨",
    "Mi corazón está lleno de amor y compasión 💖🌸",
    "Confío en mi intuición y en mis decisiones 🦋💫",
    "Soy digna de todas las bendiciones que recibo 🙏✨",
    "Mi presencia ilumina la vida de quienes me rodean 🌟💖",
    "Abrazo los cambios con valentía y optimismo 🌈💪",
    "Mi sabiduría crece con cada experiencia vivida 📚🌱",
    "Soy una mujer resiliente que aprende de cada desafío 💪🌟",
    "Mi paz interior es mi mayor fortaleza 🕊️💫",
    "Me adapto con gracia a los cambios de la vida 🦋✨",
    "Cada día me amo y me acepto más a mí misma 💖🌸",
    "Mi experiencia es un regalo que comparto con otros 🎁💫",
    "Soy una fuente de inspiración y fortaleza 💫⭐️",
    "Mi vida está llena de posibilidades infinitas 🌈✨",
    "Merezco momentos de paz y tranquilidad 🕊️💖",
    "Mi corazón está abierto a nuevas experiencias 💝🌟",
    "Soy capaz de manejar cualquier situación con calma 🧘‍♀️✨",
    "Mi intuición me guía hacia lo mejor para mí 🎯💫",
    "Cada día es una nueva oportunidad para crecer 🌱⭐️",
    "Soy una mujer valiosa y única 👑💖",
    "Mi amor propio crece cada día más 💝✨",
    "Confío en el proceso de la vida 🌈🙏",
    "Soy merecedora de respeto y consideración 👑💫",
    "Mi presencia aporta valor al mundo 🌟💖",
    "Cada experiencia me hace más fuerte 💪✨",
    "Mi sabiduría interior me guía siempre 🎯🌟",
    "Soy capaz de crear la vida que deseo 🌈💫",
    "Mi paz mental es una prioridad 🕊️💖",
    "Acepto mi pasado y abrazo mi presente 🙏✨",
    "Soy una mujer completa y realizada 👑💝",
    "Mi corazón está lleno de gratitud 💖🌸",
    "Cada día es un regalo por descubrir 🎁✨",
    "Mi fuerza interior es inquebrantable 💪🌟",
    "Soy digna de amor y respeto 👑💖",
    "Mi vida está llena de bendiciones 🙏✨",
    "Confío en mi capacidad para resolver problemas 🎯💫",
    "Mi experiencia es mi mayor maestra 📚🌱",
    "Soy una mujer sabia y compasiva 🕊️💖",
    "Cada día me acerco más a mis metas 🎯✨",
    "Mi presencia es un regalo para otros 🎁💫",
    "Soy fuerte ante la adversidad 💪🌟",
    "Mi corazón está en paz 🕊️💖",
    "Acepto los cambios con serenidad 🦋✨",
   "Mi vida está llena de oportunidades maravillosas 🌈✨",
    "Soy una mujer que inspira a otros 💫👑",
    "Mi sabiduría crece con cada experiencia 📚💖",
    "Confío en el proceso de mi vida 🙏✨",
    "Soy merecedora de paz y felicidad 🕊️💫",
    "Mi amor propio es mi prioridad 💝🌟",
    "Cada día me convierto en una mejor versión de mí misma 🌱✨",
    "Mi intuición es mi mejor guía 🎯💫",
    "Soy una mujer valiente y decidida 💪👑",
    "Mi presencia trae luz a los demás ⭐️💖",
    "Acepto mis emociones con compasión 🤗💕",
    "Mi experiencia de vida es valiosa 📚✨",
    "Soy digna de abundancia y prosperidad 💫💎",
    "Mi corazón está abierto al amor 💖🌸",
    "Cada día es una nueva aventura 🌅✨",
    "Mi fortaleza interior es infinita 💪🌟",
    "Soy una mujer en constante crecimiento 🌱💫",
    "Mi paz interior es inquebrantable 🕊️💖",
    "Confío en mi capacidad de adaptación 🦋✨",
    "Soy merecedora de respeto y admiración 👑💫",
    "Mi vida tiene un propósito especial 🎯💖",
    "Cada experiencia me hace más sabia 📚🌟",
    "Mi presencia es un regalo para el mundo 🎁✨",
    "Soy capaz de superar cualquier obstáculo 💪💫",
    "Mi corazón está lleno de esperanza 💖🌈",
    "Acepto el cambio como parte del crecimiento 🌱✨",
    "Mi sabiduría interior me guía siempre 🎯🌟",
    "Soy una mujer llena de luz y amor 💫💖",
    "Mi vida es un hermoso viaje de autodescubrimiento 🦋✨",
    "Confío en mi poder interior 💪👑",
    "Mi presencia es valiosa y necesaria 🌟💫",
    "Soy digna de amor y respeto incondicional 💝✨",
    "Cada día es una oportunidad para brillar ⭐️💖",
    "Mi fortaleza crece con cada desafío 💪🌟",
    "Soy una mujer resiliente y poderosa 👑💫",
    "Mi corazón está en paz con mi pasado 🕊️💖",
    "Acepto mi presente con gratitud 🙏✨",
    "Mi experiencia me hace única y especial 💫🌟",
    "Soy capaz de crear mi propia felicidad 🌈💖",
    "Mi intuición nunca me falla 🎯✨",
    "Cada día me amo más a mí misma 💝🌸",
    "Mi presencia inspira positividad 🌟💫",
    "Soy una mujer sabia y compasiva 📚💖",
    "Mi vida está llena de bendiciones infinitas 🙏✨",
    "Confío en el tiempo de Dios 🕊️💫",
    "Mi fuerza interior es mi mayor aliada 💪🌟",
    "Soy merecedora de todo lo bueno 👑💖",
    "Mi corazón está abierto a nuevas experiencias 🦋✨",
    "Acepto los cambios con serenidad y gracia 🌱💫",
    "Mi sabiduría crece día a día 📚🌟",
    "Soy una mujer que inspira a otros 💫💖",
    "Mi presencia trae paz y armonía 🕊️✨",
    "Confío en mi camino de vida 🎯💫",
    "Mi amor propio es incondicional 💝🌟",
    "Cada día es un nuevo comienzo 🌅💖",
    "Soy fuerte y capaz en todo momento 💪✨",
    "Mi corazón está lleno de gratitud 🙏💫",
    "Acepto mi edad como un regalo 🎁🌟",
    "Mi experiencia es mi mayor tesoro 📚💖",
    "Soy digna de éxito y reconocimiento 👑✨",
    "Mi presencia ilumina cada espacio 🌟💫",
    "Confío en mi proceso de crecimiento 🌱💖",
    "Mi paz interior es mi prioridad 🕊️✨",
    "Cada día me acerco más a mis sueños 💫🌟",
    "Soy una mujer valiente y decidida 💪👑",
    "Mi corazón está lleno de amor propio 💝💖",
    "Acepto mi cuerpo con amor y respeto 🤗✨",
    "Mi sabiduría me guía en cada decisión 🎯💫",
    "Soy merecedora de amor verdadero 💖🌟",
    "Mi presencia es un regalo para otros 🎁✨",
    "Confío en mi intuición femenina 🦋💫",
    "Mi fortaleza interior es inquebrantable 💪🌟",
    "Cada día es una bendición 🙏💖",
    "Soy una mujer en constante evolución 🌱✨",
    "Mi corazón está en paz con mi presente 🕊️💫",
    "Acepto mis emociones sin juzgarlas 💝🌟",
    "Mi experiencia me hace más sabia 📚💖",
    "Soy digna de abundancia en mi vida ✨💎",
    "Mi presencia trae alegría a otros 🌟💫",
    "Confío en mi capacidad de amar 💖🌸",
    "Mi fuerza interior crece cada día 💪✨",
    "Cada momento es una oportunidad de aprendizaje 📚🌟",
    "Soy una mujer auténtica y única 👑💫",
    "Mi corazón está abierto a la abundancia 💝✨",
    "Acepto mi pasado con gratitud 🙏💖",
    "Mi sabiduría es mi mayor fortaleza 🎯🌟",
    "Soy merecedora de paz y tranquilidad 🕊️💫",
    "Mi presencia marca la diferencia 💫✨",
    "Confío en el proceso de la vida 🌱💖",
    "Mi amor propio es mi mayor victoria 💝🌟",
    "Cada día me siento más plena 🌈✨",
    "Soy una mujer resiliente y fuerte 💪👑",
    "Mi corazón está lleno de esperanza 💖🌟",
    "Acepto los desafíos como oportunidades 🎯💫",
    "Mi experiencia enriquece mi vida 📚✨",
    "Soy digna de respeto y admiración 👑💖",
    "Mi presencia inspira a otros 🌟💫",
    "Confío en mi sabiduría interior 🎯🌸",
    "Mi fortaleza no tiene límites 💪✨",
    "Cada día es un nuevo regalo 🎁💫",
    "Soy una mujer llena de luz 💫👑",
    "Mi corazón está en paz y armonía 🕊️💖",
    "Acepto mi presente con amor 💝✨",
    "Mi intuición me guía siempre 🦋🌟",
    "Soy merecedora de todo lo bueno 👑💫",
    "Mi vida es un hermoso viaje de autodescubrimiento 🌅💫",
    "Soy una mujer que irradia confianza 👑✨",
    "Mi sabiduría crece con cada experiencia 📚💖",
    "Confío en mi poder interior 💪🌟",
    "Mi corazón está abierto al crecimiento 🌱💫",
    "Cada día es una nueva oportunidad 🎁✨",
    "Soy digna de amor y respeto 💝👑",
    "Mi presencia trae paz a otros 🕊️💖",
    "Acepto mi edad con orgullo y gratitud 🙏✨",
    "Mi intuición es mi mejor consejera 🎯💫",
    "Soy una mujer fuerte y determinada 💪🌟",
    "Mi vida está llena de posibilidades infinitas 🌈💖",
    "Confío en mi proceso personal 🦋✨",
    "Mi amor propio crece cada día 💝💫",
    "Cada experiencia me hace más sabia 📚🌟",
    "Soy merecedora de paz y felicidad 🕊️👑",
    "Mi presencia ilumina el camino 🌟💖",
    "Acepto mis emociones con compasión 🤗✨",
    "Mi fortaleza interior es inquebrantable 💪💫",
    "Cada día me acerco más a mis metas 🎯🌟",
    "Soy una mujer valiosa y única 👑💖",
    "Mi corazón está lleno de gratitud 🙏✨",
    "Confío en el tiempo divino 🕊️💫",
    "Mi sabiduría me guía siempre 📚🌟",
    "Cada momento es precioso 💎✨",
    "Soy capaz de superar cualquier obstáculo 💪👑",
    "Mi presencia es un regalo 🎁💖",
    "Acepto el cambio con gracia 🦋✨",
    "Mi intuición nunca me falla 🎯💫",
    "Soy una mujer en constante evolución 🌱🌟",
    "Mi corazón está en paz 🕊️💖",
    "Confío en mi capacidad de adaptación 💫✨",
    "Mi amor propio es incondicional 💝👑",
    "Cada día es una nueva aventura 🌅💖",
    "Soy fuerte ante la adversidad 💪🌟",
    "Mi presencia inspira a otros ⭐️✨",
    "Acepto mi cuerpo con amor 💝💫",
    "Mi experiencia es valiosa 📚🌟",
    "Soy digna de abundancia 👑💖",
    "Mi corazón está abierto al amor 💕✨",
    "Confío en mi camino 🎯💫",
    "Mi fortaleza crece cada día 💪🌟",
    "Cada momento es una bendición 🙏💖",
    "Soy una mujer resiliente 👑✨",
    "Mi presencia trae luz 🌟💫",
    "Acepto mi pasado con gratitud 🙏🌟",
    "Mi sabiduría es mi guía 📚💖",
    "Cada día es un regalo 🎁✨",
    "Soy merecedora de respeto 👑💫",
    "Mi corazón está en armonía 🕊️🌟",
    "Confío en mi poder personal 💪💖",
    "Mi intuición me protege 🎯✨",
    "Soy una mujer auténtica 👑💫",
    "Mi presencia es valiosa 🌟🌸",
    "Acepto mi presente con amor 💝✨",
    "Mi fortaleza es infinita 💪🌟",
    "Cada día me amo más 💖💫",
    "Soy digna de éxito 👑✨",
    "Mi corazón está en paz 🕊️🌟",
    "Confío en mi sabiduría 📚💖",
    "Mi amor propio es mi prioridad 💝✨",
    "Cada experiencia me fortalece 💪💫",
    "Soy una mujer valiente 👑🌟",
    "Mi presencia hace la diferencia 🌟💖",
    "Acepto mis logros con humildad 🙏✨",
    "Mi intuición es poderosa 🎯💫",
    "Soy capaz de todo 💪🌟",
    "Mi corazón está lleno de luz 💖✨",
    "Confío en mi proceso 🦋💫",
    "Mi sabiduría crece día a día 📚🌟",
    "Cada momento cuenta 💎💖",
    "Soy una mujer completa 👑✨",
    "Mi presencia es necesaria 🌟💫",
    "Acepto mi poder interior 💪🌟",
    "Mi fortaleza me define 💖✨",
    "Cada día es una oportunidad 🎁💫",
    "Soy merecedora de felicidad 👑🌟",
    "Mi corazón es mi guía 💝💖",
    "Confío en mi destino 🎯✨",
    "Mi amor propio es mi fuerza 💪💫",
    "Cada paso me acerca a mis sueños 🌟🌸",
    "Soy una mujer extraordinaria 👑✨",
    "Mi presencia transmite paz 🕊️💫",
    "Acepto mi unicidad 💝🌟",
    "Mi sabiduría es mi tesoro 📚💖",
    "Cada día es especial 🌅✨",
    "Soy digna de amor verdadero 👑💫",
    "Mi corazón está abierto 💖🌟",
    "Confío en mi intuición 🎯✨",
    "Mi fortaleza es mi aliada 💪💫",
    "Cada momento es perfecto 🌟💖",
    "Soy una mujer sabia 📚✨",
    "Mi presencia es un regalo 🎁🌟",
    "Acepto mi camino con amor 💝💫",
    "Mi poder interior es infinito 💪💖",
    "Cada día es una bendición 🙏✨",
    "Soy merecedora de paz 🕊️🌟",
    "Mi corazón está agradecido 💖💫",
    "Confío en mi capacidad 💪✨",
    "Mi amor propio es invaluable 💝🌟",
    "Cada experiencia es un regalo 🎁💖",
    "Soy una mujer inspiradora 👑✨",
    "Mi presencia es importante 🌟💫",
    "Mi vida es un hermoso viaje de autodescubrimiento 🌅💫",
    "Soy una mujer que irradia confianza 👑✨",
    "Mi sabiduría crece con cada experiencia 📚💖",
    "Confío en mi poder interior 💪🌟",
    "Mi corazón está abierto al crecimiento 🌱💫",
    "Cada día es una nueva oportunidad 🎁✨",
    "Soy digna de amor y respeto 💝👑",
    "Mi presencia trae paz a otros 🕊️💖",
    "Acepto mi edad con orgullo y gratitud 🙏✨",
    "Mi intuición es mi mejor consejera 🎯💫",
    "Soy una mujer fuerte y determinada 💪🌟",
    "Mi vida está llena de posibilidades infinitas 🌈💖",
    "Confío en mi proceso personal 🦋✨",
    "Mi amor propio crece cada día 💝💫",
    "Cada experiencia me hace más sabia 📚🌟",
    "Soy merecedora de paz y felicidad 🕊️👑",
    "Mi presencia ilumina el camino 🌟💖",
    "Acepto mis emociones con compasión 🤗✨",
    "Mi fortaleza interior es inquebrantable 💪💫",
    "Cada día me acerco más a mis metas 🎯🌟",
    "Soy una mujer valiosa y única 👑💖",
    "Mi corazón está lleno de gratitud 🙏✨",
    "Confío en el tiempo divino 🕊️💫",
    "Mi sabiduría me guía siempre 📚🌟",
    "Cada momento es precioso 💎✨",
    "Soy capaz de superar cualquier obstáculo 💪👑",
    "Mi presencia es un regalo 🎁💖",
    "Acepto el cambio con gracia 🦋✨",
    "Mi intuición nunca me falla 🎯💫",
    "Soy una mujer en constante evolución 🌱🌟",
    "Mi corazón está en paz 🕊️💖",
    "Confío en mi capacidad de adaptación 💫✨",
    "Mi amor propio es incondicional 💝👑",
    "Cada día es una nueva aventura 🌅💖",
    "Soy fuerte ante la adversidad 💪🌟",
    "Mi presencia inspira a otros ⭐️✨",
    "Acepto mi cuerpo con amor 💝💫",
    "Mi experiencia es valiosa 📚🌟",
    "Soy digna de abundancia 👑💖",
    "Mi corazón está abierto al amor 💕✨",
    "Confío en mi camino 🎯💫",
    "Mi fortaleza crece cada día 💪🌟",
    "Cada momento es una bendición 🙏💖",
    "Soy una mujer resiliente 👑✨",
    "Mi presencia trae luz 🌟💫",
    "Acepto mi pasado con gratitud 🙏🌟",
    "Mi sabiduría es mi guía 📚💖",
    "Cada día es un regalo 🎁✨",
    "Soy merecedora de respeto 👑💫",
    "Mi corazón está en armonía 🕊️🌟",
    "Confío en mi poder personal 💪💖",
    "Mi intuición me protege 🎯✨",
    "Soy una mujer auténtica 👑💫",
    "Mi presencia es valiosa 🌟🌸",
    "Acepto mi presente con amor 💝✨",
    "Mi fortaleza es infinita 💪🌟",
    "Cada día me amo más 💖💫",
    "Soy digna de éxito 👑✨",
    "Mi corazón está en paz 🕊️🌟",
    "Confío en mi sabiduría 📚💖",
    "Mi amor propio es mi prioridad 💝✨",
    "Cada experiencia me fortalece 💪💫",
    "Soy una mujer valiente 👑🌟",
    "Mi presencia hace la diferencia 🌟💖",
    "Acepto mis logros con humildad 🙏✨",
    "Mi intuición es poderosa 🎯💫",
    "Soy capaz de todo 💪🌟",
    "Mi corazón está lleno de luz 💖✨",
    "Confío en mi proceso 🦋💫",
    "Mi sabiduría crece día a día 📚🌟",
    "Cada momento cuenta 💎💖",
    "Soy una mujer completa 👑✨",
    "Mi presencia es necesaria 🌟💫",
    "Acepto mi poder interior 💪🌟",
    "Mi fortaleza me define 💖✨",
    "Cada día es una oportunidad 🎁💫",
    "Soy merecedora de felicidad 👑🌟",
    "Mi corazón es mi guía 💝💖",
    "Confío en mi destino 🎯✨",
    "Mi amor propio es mi fuerza 💪💫",
    "Cada paso me acerca a mis sueños 🌟🌸",
    "Soy una mujer extraordinaria 👑✨",
    "Mi presencia transmite paz 🕊️💫",
    "Acepto mi unicidad 💝🌟",
    "Mi sabiduría es mi tesoro 📚💖",
    "Cada día es especial 🌅✨",
    "Soy digna de amor verdadero 👑💫",
    "Mi corazón está abierto 💖🌟",
    "Confío en mi intuición 🎯✨",
    "Mi fortaleza es mi aliada 💪💫",
    "Cada momento es perfecto 🌟💖",
    "Soy una mujer sabia 📚✨",
    "Mi presencia es un regalo 🎁🌟",
    "Acepto mi camino con amor 💝💫",
    "Mi poder interior es infinito 💪💖",
    "Cada día es una bendición 🙏✨",
    "Soy merecedora de paz 🕊️🌟",
    "Mi corazón está agradecido 💖💫",
    "Confío en mi capacidad 💪✨",
    "Mi amor propio es invaluable 💝🌟",
    "Cada experiencia es un regalo 🎁💖",
    "Soy una mujer inspiradora 👑✨",
    "Mi presencia es importante 🌟💫",
    "Mi sabiduría es mi fortaleza 📚🌟",
    "Cada día es una nueva oportunidad 🌅✨",
    "Soy digna de toda la felicidad 👑💫",
    "Mi corazón guía mis pasos 💖🌟",
    "Confío en mi crecimiento personal 🌱✨",
    "Mi fortaleza es inspiradora 💪💫",
    "Cada momento me hace más sabia 📚🌟",
    "Soy una mujer en constante evolución 🦋💖",
    "Mi presencia es significativa ⭐️✨",
    "Acepto mi vida con gratitud 🙏💫",
    "Mi intuición me guía siempre 🎯🌟",
    "Cada día traigo luz al mundo 💫💖",
    "Soy merecedora de respeto 👑✨",
    "Mi corazón está en calma 🕊️🌟",
    "Confío en mi camino único 🌈💫",
    "Mi amor propio florece 🌸💖",
    "Cada experiencia me enriquece 📚✨",
    "Soy una mujer poderosa 💪🌟",
    "Mi presencia trae armonía 🎵💫",
    "Acepto cada etapa de mi vida 🌱💖",
    "Mi sabiduría crece cada día 📚✨",
    "Cada momento es valioso 💎🌟",
    "Soy digna de abundancia 👑💫",
    "Mi corazón está lleno de amor 💖✨",
    "Confío en mi proceso vital 🌱🌟",
    "Mi fortaleza es infinita 💪💫",
    "Cada día es un nuevo comienzo 🌅💖",
    "Soy una mujer resiliente 🦋✨",
    "Mi presencia es un regalo 🎁🌟",
    "Acepto mi belleza interior 💝💫",
    "Mi intuición es mi guía 🎯💖",
    "Cada paso me fortalece 👣✨",
    "Soy merecedora de paz mental 🕊️🌟",
    "Mi corazón está agradecido 🙏💫",
    "Confío en mi sabiduría interior 📚💖",
    "Mi amor propio es inquebrantable 💝✨",
    "Cada día me acepto más 🌟💫",
    "Soy una mujer valiosa 👑🌟",
    "Mi presencia ilumina vidas ⭐️💖",
    "Acepto mis emociones 🌈✨",
    "Mi fortaleza me define 💪🌟",
    "Cada momento es una bendición 🙏💫",
    "Soy digna de amor verdadero 💖✨",
    "Mi corazón es mi brújula 🎯🌟",
    "Confío en mi poder interior 💫💖",
    "Mi sabiduría me guía 📚✨",
    "Cada día es especial 🌅🌟",
    "Soy una mujer auténtica 👑💫",
    "Mi presencia es valiosa 🌟💖",
    "Acepto mi unicidad 💝✨",
    "Mi intuición nunca falla 🎯🌟",
    "Cada experiencia me enseña 📚💫",
    "Soy merecedora de felicidad 👑💖",
    "Mi corazón está en paz 🕊️✨",
    "Confío en mis decisiones 🌟💫",
    "Mi amor propio crece 💝🌸",
    "Cada día soy más fuerte 💪✨",
    "Soy una mujer sabia 📚🌟",
    "Mi presencia transmite paz 🕊️💫",
    "Acepto mi camino 🌱💖",
    "Mi fortaleza es mi aliada 💪✨",
    "Cada momento es perfecto 🌟🌸",
    "Soy digna de respeto 👑💫",
    "Mi corazón está abierto 💖✨",
    "Confío en mi destino 🎯🌟",
    "Mi sabiduría es valiosa 📚💫",
    "Cada día es un regalo 🎁💖",
    "Soy una mujer completa 👑✨",
    "Mi presencia hace diferencia 🌟🌸",
    "Acepto mi poder personal 💪💫",
    "Mi intuición me protege 🎯💖",
    "Cada paso cuenta 👣✨",
    "Soy merecedora de abundancia 💎🌟",
    "Mi corazón está tranquilo 🕊️💫",
    "Confío en mi proceso 🌱💖",
    "Mi amor propio es esencial 💝✨",
    "Cada día me transformo 🦋🌟",
    "Soy una mujer inspiración 👑💫",
    "Mi presencia es necesaria ⭐️💖",
    "Acepto mi historia 📚✨",
    "Mi fortaleza es admirable 💪🌟",
    "Cada momento me construye 🌱💫",
    "Soy digna de éxito 👑💖",
    "Mi corazón es sabio 💝✨",
    "Confío en mi luz interior 🌟🌸",
    "Mi sabiduría florece 📚💫",
    "Cada día es bendecido 🙏💖",
    "Soy una mujer única 👑✨",
    "Mi presencia es luz 🌟🌸",
    "Acepto mi presente 💝💫",
    "Mi intuición es certera 🎯💖",
    "Cada paso me fortalece 💪✨",
    "Soy merecedora de amor 💖🌟",
    "Mi corazón es mi guía 🎯💫",
    "Confío en mi sabiduría 📚💖",
    "Mi amor propio es mi base 💝✨",
    "Cada día es nuevo 🌅🌟",
    "Soy una mujer valiente 👑💫",
    "Mi presencia inspira 🌟💖",
    "Acepto mi crecimiento 🌱✨",
    "Mi fortaleza brilla 💪🌟",
    "Cada momento es único 💎💫"
];
   export const agradecimientos = [
    "Gracias vida por cada nuevo amanecer 🌅✨",
    "Gracias Dios por tu amor infinito 🙏💫",
    "Agradezco cada experiencia que me hace crecer 🌱💖",
    "Gracias por la paz en mi corazón 🕊️✨",
    "Agradezco la sabiduría que me da la vida 📚🌟",
    "Gracias por mi fortaleza interior 💪💫",
    "Agradezco el amor que me rodea 💝💖",
    "Gracias por cada bendición recibida 🙏✨",
    "Agradezco la belleza de cada día 🌸🌟",
    "Gracias por mi familia y amigos 👨‍👩‍👧‍👦💫",
    "Agradezco las lecciones aprendidas 📖💖",
    "Gracias por la abundancia en mi vida 💎✨",
    "Agradezco la salud que disfruto 🏃‍♀️🌟",
    "Gracias por los momentos de alegría 😊💫",
    "Agradezco la fuerza para seguir adelante 💪💖",
    "Gracias por la luz en mi camino 🌟✨",
    "Agradezco cada sonrisa recibida 😊🌟",
    "Gracias por el aire que respiro 🌬️💫",
    "Agradezco la paz en mi mente 🧘‍♀️💖",
    "Gracias por el amor propio 💝✨",
    "Gracias por cada nuevo aprendizaje 📚✨",
    "Agradezco la capacidad de amar 💝🌟",
    "Gracias por mi fortaleza diaria 💪💫",
    "Agradezco la belleza de la naturaleza 🌳💖",
    "Gracias por el don de la vida 🎁✨",
    "Agradezco cada abrazo recibido 🤗🌟",
    "Gracias por la esperanza en mi corazón 💖💫",
    "Agradezco las pequeñas alegrías 😊✨",
    "Gracias por la paz interior 🕊️🌟",
    "Agradezco el poder de la oración 🙏💫",
    "Gracias por cada nuevo reto 🎯💖",
    "Agradezco la sabiduría adquirida 📚✨",
    "Gracias por el amor incondicional 💝🌟",
    "Agradezco los momentos de silencio 🧘‍♀️💫",
    "Gracias por la fe que me sostiene ✝️💖",
    "Agradezco las bendiciones diarias 🙏✨",
    "Gracias por la luz divina 🌟🌟",
    "Agradezco el poder de sanar 💖💫",
    "Gracias por cada sonrisa 😊✨",
    "Agradezco la fuerza interior 💪🌟",
    "Gracias por los buenos momentos 🎉💫",
    "Agradezco el don del perdón 🕊️💖",
    "Gracias por la abundancia 💎✨",
    "Agradezco las mañanas soleadas ☀️🌟",
    "Gracias por la salud mental 🧠💫",
    "Agradezco el poder de crecer 🌱💖",
    "Gracias por la paciencia 🙏✨",
    "Agradezco la compañía divina 👼🌟",
    "Gracias por cada logro alcanzado 🎯💫",
    "Agradezco el amor propio 💝💖",
    "Gracias por la serenidad 🕊️✨",
    "Agradezco los buenos consejos 📝🌟",
    "Gracias por la protección divina 🛡️💫",
    "Agradezco cada experiencia vivida 📚💖",
    "Gracias por la fortaleza mental 🧠✨",
    "Agradezco el poder de la gratitud 🙏🌟",
    "Gracias por los momentos de paz 🕊️💫",
    "Agradezco la sabiduría divina 📖💖",
    "Gracias por el amor familiar 👨‍👩‍👧‍👦✨",
    "Agradezco la bondad recibida 🤲🌟",
    "Gracias por cada amanecer 🌅💫",
    "Agradezco la capacidad de soñar 💭💖",
    "Gracias por la vida plena ✨🌟",
    "Agradezco las bendiciones ocultas 🎁💫",
    "Gracias por la alegría de vivir 😊💖",
    "Agradezco el poder de la fe 🙏✨",
    "Gracias por los buenos amigos 👥🌟",
    "Agradezco cada respiro 🌬️💫",
    "Gracias por la luz interior 💖✨",
    "Agradezco el don de la vida 🎁🌟",
    "Gracias por los momentos felices 😊💫",
    "Agradezco la fuerza para continuar 💪💖",
    "Gracias por la paz mental 🧘‍♀️✨",
    "Agradezco el amor universal 💝🌟",
    "Gracias por cada bendición 🙏💫",
    "Agradezco la sabiduría del tiempo ⏳💖",
    "Gracias por la esperanza 🌟✨",
    "Agradezco los nuevos comienzos 🌅🌟",
    "Gracias por la salud física 🏃‍♀️💫",
    "Agradezco el poder del amor 💝💖",
    "Gracias por la tranquilidad 🕊️✨",
    "Agradezco las lecciones de vida 📚🌟",
    "Gracias por la prosperidad 💎💫",
    "Agradezco la paz del corazón 💖✨",
    "Gracias por el crecimiento personal 🌱🌟",
    "Agradezco la guía divina 🙏💫",
    "Gracias por los buenos pensamientos 💭💖",
    "Agradezco la capacidad de perdonar 🕊️✨",
    "Gracias por cada oportunidad 🎯🌟",
    "Agradezco el poder de la mente 🧠💫",
    "Gracias por los momentos de reflexión 🤔💖",
    "Agradezco la abundancia de amor 💝✨",
    "Gracias por la fortaleza espiritual 🙏🌟",
    "Agradezco cada nuevo día ☀️💫",
    "Gracias por la capacidad de ayudar 🤝💖",
    "Agradezco las bendiciones inesperadas 🎁✨",
    "Gracias por la luz del sol ☀️🌟",
    "Agradezco el poder de la gratitud 🙏💫",
    "Gracias por la paz interior 🕊️💖",
    "Agradezco el amor divino ✝️✨",
    "Gracias por cada sonrisa 😊🌟",
    "Agradezco la fuerza interior 💪💫",
    "Gracias por los buenos recuerdos 📸💖",
    "Agradezco el poder de crear 🎨✨",
    "Gracias por la sabiduría adquirida 📚🌟",
    "Agradezco la belleza de la vida 🌸💫",
    "Gracias por el amor propio 💝💖",
    "Agradezco los momentos de calma 🧘‍♀️✨",
    "Gracias por la protección divina 👼🌟",
    "Agradezco cada experiencia 📖💫",
    "Gracias por la salud emocional 💖✨",
    "Agradezco el poder de la fe 🙏🌟",
    "Gracias por los buenos momentos 🎉💫",
    "Agradezco la paz mental 🧠💖",
    "Gracias por el amor universal 💝✨",
    "Agradezco las bendiciones diarias 🌟💫",
    "Gracias por la fortaleza mental 💪💖",
    "Agradezco el poder del perdón 🕊️✨",
    "Gracias por cada logro 🎯🌟",
    "Agradezco la abundancia recibida 💎💫",
    "Gracias por la luz en mi camino ⭐️💖",
    "Gracias por la esperanza en mi corazón 💖✨",
    "Agradezco la capacidad de amar 💝🌟",
    "Gracias por cada nuevo despertar 🌅💫",
    "Agradezco la sabiduría divina 📖💖",
    "Gracias por el poder de la oración 🙏✨",
    "Agradezco los pequeños milagros ✨🌟",
    "Gracias por la fuerza interior 💪💫",
    "Agradezco el amor incondicional 💝💖",
    "Gracias por las bendiciones diarias 🙏✨",
    "Agradezco la paz en mi alma 🕊️🌟",
    "Gracias por la luz divina ✨💫",
    "Agradezco cada respiración 🌬️💖",
    "Gracias por la alegría de vivir 😊✨",
    "Agradezco los momentos de reflexión 🤔🌟",
    "Gracias por la abundancia 💎💫",
    "Agradezco la guía espiritual 🙏💖",
    "Gracias por cada sonrisa 😊✨",
    "Agradezco el don de la vida 🎁🌟",
    "Gracias por la serenidad 🕊️💫",
    "Agradezco el poder de crecer 🌱💖",
    "Gracias por la salud mental 🧠✨",
    "Agradezco la compañía divina 👼🌟",
    "Gracias por cada logro 🎯💫",
    "Agradezco el amor propio 💝💖",
    "Gracias por la protección divina 🛡️✨",
    "Agradezco los buenos consejos 📝🌟",
    "Gracias por cada experiencia 📚💫",
    "Agradezco la fortaleza mental 💪💖",
    "Gracias por el poder de la fe ✝️✨",
    "Agradezco los momentos de paz 🕊️🌟",
    "Gracias por el amor familiar 👨‍👩‍👧‍👦💫",
    "Agradezco la bondad recibida 🤲💖",
    "Gracias por cada amanecer 🌅✨",
    "Agradezco la capacidad de soñar 💭🌟",
    "Gracias por la vida plena ✨💫",
    "Agradezco las bendiciones ocultas 🎁💖",
    "Gracias por la alegría cotidiana 😊✨",
    "Agradezco el poder de la gratitud 🙏🌟",
    "Gracias por los buenos amigos 👥💫",
    "Agradezco cada respiro de vida 🌬️💖",
    "Gracias por la luz interior 💖✨",
    "Agradezco el don del tiempo ⏳🌟",
    "Gracias por los momentos felices 😊💫",
    "Agradezco la fuerza para seguir 💪💖",
    "Gracias por la paz mental 🧘‍♀️✨",
    "Agradezco el amor universal 💝🌟",
    "Gracias por cada bendición 🙏💫",
    "Agradezco la sabiduría adquirida 📚💖",
    "Gracias por la esperanza ⭐️✨",
    "Agradezco los nuevos comienzos 🌅🌟",
    "Gracias por la salud física 🏃‍♀️💫",
    "Agradezco el poder del amor 💝💖",
    "Gracias por la tranquilidad 🕊️✨",
    "Agradezco las lecciones de vida 📖🌟",
    "Gracias por la prosperidad 💎💫",
    "Agradezco la paz del corazón 💖✨",
    "Gracias por el crecimiento personal 🌱🌟",
    "Agradezco la guía espiritual 🙏💫",
    "Gracias por los buenos pensamientos 💭💖",
    "Agradezco la capacidad de perdonar 🕊️✨",
    "Gracias por cada oportunidad 🎯🌟",
    "Agradezco el poder mental 🧠💫",
    "Gracias por la reflexión diaria 🤔💖",
    "Agradezco la abundancia de amor 💝✨",
    "Gracias por la fortaleza espiritual 🙏🌟",
    "Agradezco cada momento presente ⏰💫",
    "Gracias por poder ayudar a otros 🤝💖",
    "Agradezco las sorpresas de la vida 🎁✨",
    "Gracias por la luz del día ☀️🌟",
    "Agradezco la actitud positiva 😊💫",
    "Gracias por la paz interior 🕊️💖",
    "Agradezco el amor divino ✝️✨",
    "Gracias por cada abrazo 🤗🌟",
    "Agradezco la fuerza interior 💪💫",
    "Gracias por los buenos recuerdos 📸💖",
    "Agradezco el don de crear 🎨✨",
    "Gracias por las enseñanzas 📚🌟",
    "Agradezco la belleza de vivir 🌸💫",
    "Gracias por el autocuidado 💝💖",
    "Agradezco los momentos de calma 🧘‍♀️✨",
    "Gracias por la protección angelical 👼🌟",
    "Agradezco cada experiencia vital 📖💫",
    "Gracias por la salud emocional 💖✨",
    "Agradezco el poder de creer 🙏🌟",
    "Gracias por las alegrías 🎉💫",
    "Agradezco la claridad mental 🧠💖",
    "Gracias por el amor universal 💝✨",
    "Agradezco las bendiciones diarias 🌟💫",
    "Gracias por la resistencia mental 💪💖",
    "Agradezco el poder perdonar 🕊️✨",
    "Gracias por cada meta alcanzada 🎯🌟",
    "Agradezco la abundancia presente 💎💫",
    "Gracias por iluminar mi camino ⭐️💖",
    "Agradezco la fe inquebrantable 🙏✨",
    "Gracias por el amor propio 💝🌟",
    "Agradezco la paciencia cultivada 🧘‍♀️💫",
    "Gracias por la sabiduría ganada 📚💖",
    "Agradezco la paz encontrada 🕊️✨",
    "Gracias por la fortaleza diaria 💪🌟",
    "Agradezco las bendiciones infinitas 🙏💫",
    "Gracias por la luz en mi vida ✨💖"
];

export const versiculosBiblicos = [
    "«No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo.» - Isaías 41:10 🙏✨",
    "«Todo lo puedo en Cristo que me fortalece.» - Filipenses 4:13 💪🕊️",
    "«El Señor es mi luz y mi salvación; ¿de quién temeré?» - Salmos 27:1 🌟💖",
    "«La paz os dejo, mi paz os doy.» - Juan 14:27 🕊️✨",
    "«Echa sobre Jehová tu carga, y él te sustentará.» - Salmos 55:22 🙏💫",
    "«Confía en el Señor con todo tu corazón.» - Proverbios 3:5 💖✨",
    "«El Señor es mi pastor, nada me faltará.» - Salmos 23:1 🌟🙏",
    "«Me buscaréis y me hallaréis, porque me buscaréis de todo corazón.» - Jeremías 29:13 💖🕊️",
    "«Mas buscad primeramente el reino de Dios y su justicia.» - Mateo 6:33 👑✨",
    "«Mira que te mando que te esfuerces y seas valiente.» - Josué 1:9 💪🌟",
    "«Jehová es bueno, fortaleza en el día de la angustia.» - Nahúm 1:7 🙏💫",
    "«Deléitate en el Señor, y él te concederá los deseos de tu corazón.» - Salmos 37:4 💖✨",
    "«En paz me acostaré y dormiré, porque solo tú, oh Señor, me haces vivir confiado.» - Salmos 4:8 🕊️🌙",
    "«Más preciosa que las piedras preciosas es la sabiduría.» - Proverbios 3:15 📚💎",
    "«El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.» - Salmos 91:1 🏰✨",
    "«Jehová es mi fortaleza y mi escudo.» - Salmos 28:7 🛡️💪",
    "«La misericordia de Jehová es desde la eternidad.» - Salmos 103:17 💖🕊️",
    "«Grande es tu fidelidad.» - Lamentaciones 3:23 🙏✨",
    "«El gozo de Jehová es mi fortaleza.» - Nehemías 8:10 😊💫",
    "«En quietud y confianza será vuestra fortaleza.» - Isaías 30:15 🕊️💖",
    "«Dios es nuestro amparo y fortaleza.» - Salmos 46:1 🏰💪",
    "«El amor nunca deja de ser.» - 1 Corintios 13:8 💝✨",
    "«Jehová guardará tu salida y tu entrada.» - Salmos 121:8 🚪🙏",
    "«El Señor es mi porción.» - Lamentaciones 3:24 💖🌟",
    "«Mi Dios suplirá todo lo que os falta.» - Filipenses 4:19 ✨💫",
    "«El Señor te bendecirá y te guardará.» - Números 6:24 🙏💖",
    "«Las misericordias de Jehová son nuevas cada mañana.» - Lamentaciones 3:23 🌅✨",
    "«Todo tiene su tiempo.» - Eclesiastés 3:1 ⏳🕊️",
    "«El nombre de Jehová es torre fuerte.» - Proverbios 18:10 🏰💪",
    "«Yo sé los pensamientos que tengo acerca de vosotros.» - Jeremías 29:11 💭💖",
    "«Fiel es Dios, que no os dejará ser tentados.» - 1 Corintios 10:13 🙏✨",
    "«El amor de Dios ha sido derramado en nuestros corazones.» - Romanos 5:5 💝💫",
    "«Mi gracia te basta.» - 2 Corintios 12:9 🕊️✨",
    "«Los que esperan en Jehová tendrán nuevas fuerzas.» - Isaías 40:31 💪🌟",
    "«Yo estoy con vosotros todos los días.» - Mateo 28:20 🙏💖",
    "«La palabra de Dios es viva y eficaz.» - Hebreos 4:12 📖✨",
    "«El Señor es mi ayudador.» - Hebreos 13:6 🤝💫",
    "«Todo lo que pidiereis en oración, creyendo, lo recibiréis.» - Mateo 21:22 🙏🌟",
    "«Dios es amor.» - 1 Juan 4:8 💝✨",
    "«Tu palabra es lámpara a mis pies.» - Salmos 119:105 🔦💫",
    "«El que comenzó en vosotros la buena obra, la perfeccionará.» - Filipenses 1:6 🌱✨",
    "«En Dios solamente está acallada mi alma.» - Salmos 62:1 🕊️💖",
    "«Vestíos de amor, que es el vínculo perfecto.» - Colosenses 3:14 💝✨",
    "«La paz de Dios guardará vuestros corazones.» - Filipenses 4:7 🕊️💖",
    "«El Señor es mi roca y mi fortaleza.» - Salmos 18:2 🏰💪",
    "«Jehová es mi luz y mi salvación.» - Salmos 27:1 🌟✨",
    "«Dios es el que en vosotros produce el querer como el hacer.» - Filipenses 2:13 💫🙏",
    "«El amor es paciente, es bondadoso.» - 1 Corintios 13:4 💝🕊️",
    "«Con Cristo estoy juntamente crucificado.» - Gálatas 2:20 ✝️💖",
    "«No os dejéis vencer por el mal.» - Romanos 12:21 💪✨",
    "«El Señor es mi porción.» - Salmos 119:57 💖🌟",
    "«Mi alma tiene sed de Dios.» - Salmos 42:2 💭🙏",
    "«Grande es tu fidelidad.» - Lamentaciones 3:23 ✨💫",
    "«El amor cubrirá multitud de pecados.» - 1 Pedro 4:8 💝🕊️",
    "«Jehová cumplirá su propósito en mí.» - Salmos 138:8 🎯💖",
    "«Mis pensamientos no son vuestros pensamientos.» - Isaías 55:8 💭✨",
    "«El Señor es bueno, fortaleza en el día de la angustia.» - Nahúm 1:7 💪🙏",
    "«Tu palabra es verdad.» - Juan 17:17 📖✨",
    "«El amor de Cristo nos constriñe.» - 2 Corintios 5:14 💝💫",
    "«Jehová es mi porción.» - Salmos 119:57 💖🌟",
    "«Mi yugo es fácil y ligera mi carga.» - Mateo 11:30 🕊️✨",
    "«El que cree en mí, tiene vida eterna.» - Juan 6:47 💫🙏",
    "«La fe es la certeza de lo que se espera.» - Hebreos 11:1 💭✨",
    "«El Señor es mi socorro.» - Hebreos 13:6 🤝💖",
    "«Yo soy el camino, la verdad y la vida.» - Juan 14:6 🛣️✨",
    "«El amor es sufrido, es benigno.» - 1 Corintios 13:4 💝🕊️",
    "«Mi Dios, pues, suplirá todo lo que os falta.» - Filipenses 4:19 ✨💫",
    "«En ti confían los que conocen tu nombre.» - Salmos 9:10 🙏💖",
    "«El Señor es mi pastor.» - Salmos 23:1 🐑✨",
    "«Tu gracia me basta.» - 2 Corintios 12:9 🕊️💫",
    "«El amor nunca deja de ser.» - 1 Corintios 13:8 💝🌟",
    "«Yo estaré con tu boca.» - Éxodo 4:12 💭✨",
    "«El Señor es mi luz.» - Salmos 27:1 🌟💖",
    "«Mi paz os doy.» - Juan 14:27 🕊️✨",
    "«Todo lo puedo en Cristo.» - Filipenses 4:13 💪💫",
    "«Dios es nuestro amparo.» - Salmos 46:1 🏰💖",
    "«La verdad os hará libres.» - Juan 8:32 📖✨",
    "«El amor de Dios es perfecto.» - 1 Juan 4:18 💝🕊️",
    "«Mi gracia es suficiente.» - 2 Corintios 12:9 🙏💫",
    "«El Señor es mi refugio.» - Salmos 91:2 🏰💖",
    "«La fe obra por el amor.» - Gálatas 5:6 💝✨",
    "«Yo soy la luz del mundo.» - Juan 8:12 🌟💫",
    "«El Señor es mi ayudador.» - Hebreos 13:6 🤝💖",
    "«Tu palabra es verdad.» - Juan 17:17 📖✨",
    "«El amor es paciente.» - 1 Corintios 13:4 💝🕊️",
    "«Mi Dios proveerá.» - Filipenses 4:19 ✨💫",
    "«El Señor es mi fortaleza.» - Éxodo 15:2 💪💖",
    "«La paz os dejo.» - Juan 14:27 🕊️✨",
    "«Fiel es Dios.» - 1 Corintios 1:9 🙏💫",
    "«El amor todo lo sufre.» - 1 Corintios 13:7 💝🌟",
    "«Yo soy el buen pastor.» - Juan 10:11 🐑✨",
    "«El Señor es mi salvación.» - Salmos 27:1 💖💫",
    "«Tu palabra es lámpara.» - Salmos 119:105 🔦✨",
    "«El amor es bondadoso.» - 1 Corintios 13:4 💝🕊️",
    "«Mi gracia te basta.» - 2 Corintios 12:9 🙏💫",
    "«El Señor es mi escudo.» - Salmos 28:7 🛡️💖",
    "«La fe sin obras es muerta.» - Santiago 2:20 💭✨",
    "«El amor todo lo espera.» - 1 Corintios 13:7 💝🌟",
    "«Yo soy la resurrección.» - Juan 11:25 ✝️💫",
    "«El Señor es mi roca.» - Salmos 18:2 🏰💖",
    "«Tu palabra es eterna.» - Salmos 119:89 📖✨",
    "«El amor no tiene temor.» - 1 Juan 4:18 💝🕊️",
    "«Guarda mi alma y líbrame.» - Salmos 25:20 🙏💫",
    "«Como el ciervo brama por las corrientes de las aguas.» - Salmos 42:1 🦌💖",
    "«Sobre toda cosa guardada, guarda tu corazón.» - Proverbios 4:23 💝✨",
    "«En el principio creó Dios los cielos y la tierra.» - Génesis 1:1 🌎🌟",
    "«Por la fe andamos, no por vista.» - 2 Corintios 5:7 👣💫",
    "«Mejor es confiar en Jehová que confiar en el hombre.» - Salmos 118:8 🙏💖",
    "«Los que siembran con lágrimas, con regocijo segarán.» - Salmos 126:5 🌱✨",
    "«Jehová es mi luz y mi salvación.» - Salmos 27:1 🌟🕊️",
    "«Porque de tal manera amó Dios al mundo.» - Juan 3:16 💝💫",
    "«Bienaventurados los pacificadores.» - Mateo 5:9 🕊️💖",
    "«Clama a mí, y yo te responderé.» - Jeremías 33:3 📞✨",
    "«Sean gratos los dichos de mi boca.» - Salmos 19:14 🗣️💫",
    "«No os conforméis a este siglo.» - Romanos 12:2 🌱💖",
    "«Examíname, oh Dios, y conoce mi corazón.» - Salmos 139:23 💝🔍",
    "«Bendice, alma mía, a Jehová.» - Salmos 103:1 🙏✨",
    "«Bástate mi gracia.» - 2 Corintios 12:9 🕊️💫",
    "«Velad y orad.» - Mateo 26:41 👀🙏",
    "«Las cosas viejas pasaron.» - 2 Corintios 5:17 🔄✨",
    "«El principio de la sabiduría es el temor de Jehová.» - Proverbios 1:7 📚💫",
    "«Bienaventurado el varón que no anduvo en consejo de malos.» - Salmos 1:1 👣💖",
    "«Lámpara es a mis pies tu palabra.» - Salmos 119:105 🔦✨",
    "«No se turbe vuestro corazón.» - Juan 14:1 💝🕊️",
    "«Jehová es mi refugio.» - Salmos 91:9 🏰💫",
    "«El que tiene oídos para oír, oiga.» - Mateo 11:15 👂✨",
    "«Dad gracias en todo.» - 1 Tesalonicenses 5:18 🙏💖",
    "«Pedid, y se os dará.» - Mateo 7:7 🎁💫",
    "«Jehová es mi libertador.» - 2 Samuel 22:2 🔓✨",
    "«No temas, cree solamente.» - Marcos 5:36 💪💖",
    "«Yo soy el Alfa y la Omega.» - Apocalipsis 1:8 🔄💫",
    "«Al que cree todo le es posible.» - Marcos 9:23 💫✨",
    "«No os afanéis por el día de mañana.» - Mateo 6:34 🌅💖",
    "«Bienaventurados los de limpio corazón.» - Mateo 5:8 💝✨",
    "«La oración del justo puede mucho.» - Santiago 5:16 🙏💫",
    "«Yo soy el pan de vida.» - Juan 6:35 🍞💖",
    "«El que perseverare hasta el fin.» - Mateo 24:13 🎯✨",
    "«La lengua apacible es árbol de vida.» - Proverbios 15:4 🌳💫",
    "«Sed hacedores de la palabra.» - Santiago 1:22 👣💖",
    "«Jehová es mi porción.» - Salmos 16:5 💝✨",
    "«Si Dios es por nosotros, ¿quién contra nosotros?» - Romanos 8:31 🛡️💫",
    "«Yo soy la vid verdadera.» - Juan 15:1 🌿💖",
    "«No nos cansemos de hacer bien.» - Gálatas 6:9 💪✨",
    "«Sed sobrios, y velad.» - 1 Pedro 5:8 👀💫",
    "«En el amor no hay temor.» - 1 Juan 4:18 💝🕊️",
    "«Regocijaos en el Señor siempre.» - Filipenses 4:4 😊✨",
    "«A Jehová tu Dios adorarás.» - Mateo 4:10 🙏💫",
    "«La palabra de Dios permanece para siempre.» - 1 Pedro 1:25 📖💖",
    "«Mansedumbre para con todos los hombres.» - Tito 3:2 🤝✨",
    "«El Señor es mi ayudador.» - Salmos 54:4 💪💫",
    "«No temas ni desmayes.» - Deuteronomio 31:8 💝🌟",
    "«Bienaventurados los misericordiosos.» - Mateo 5:7 🤲✨",
    "«El que tiene al Hijo tiene la vida.» - 1 Juan 5:12 ✝️💫",
    "«Todo lo soporta, todo lo cree.» - 1 Corintios 13:7 💖✨",
    "«Jehová es mi sustentador.» - Salmos 3:5 🙏💫",
    "«La verdad os hará libres.» - Juan 8:32 🔓💖",
    "«Dios es luz.» - 1 Juan 1:5 🌟✨",
    "«El amor es fuerte como la muerte.» - Cantares 8:6 💝💫",
    "«Vuestro Padre sabe lo que necesitáis.» - Mateo 6:8 👨‍👦💖",
    "«Jehová es mi herencia.» - Salmos 16:5 🎁✨",
    "«La fe es por el oír.» - Romanos 10:17 👂💫",
    "«El amor es el vínculo perfecto.» - Colosenses 3:14 💝🕊️",
    "«Yo soy la puerta.» - Juan 10:9 🚪✨",
    "«Mi yugo es fácil.» - Mateo 11:30 💫💖",
    "«Dios es espíritu.» - Juan 4:24 🕊️✨",
    "«No temáis, manada pequeña.» - Lucas 12:32 🐑💫",
    "«Jehová es justo en todos sus caminos.» - Salmos 145:17 👣💖",
    "«La paz de Dios sobrepasa todo entendimiento.» - Filipenses 4:7 🕊️✨",
    "«El amor es más fuerte que la muerte.» - Cantares 8:6 💝💫",
    "«Encomienda a Jehová tus obras.» - Proverbios 16:3 🙏💖",
    "«Bienaventurados los mansos.» - Mateo 5:5 🌟✨",
    "«El Señor conoce a los que son suyos.» - 2 Timoteo 2:19 💭💫",
    "«La fe es la sustancia de lo que se espera.» - Hebreos 11:1 💝🌟",
    "«Jehová es mi socorro.» - Salmos 118:7 🤝✨",
    "«No temas, yo te ayudo.» - Isaías 41:13 💪💫",
    "«El amor edifica.» - 1 Corintios 8:1 💝🏗️",
    "«Yo soy el buen pastor.» - Juan 10:14 🐑✨",
    "«La esperanza no avergüenza.» - Romanos 5:5 💫💖",
    "«Dios es fiel.» - 1 Corintios 10:13 🙏✨",
    "«El amor cubre multitud de pecados.» - 1 Pedro 4:8 💝🕊️",
    "«Yo soy la luz del mundo.» - Juan 8:12 🌟💫",
    "«El Señor es mi ayuda.» - Hebreos 13:6 🤝💖",
    "«La gracia sea con todos vosotros.» - Hebreos 13:25 ✨🙏",
    "«El amor es de Dios.» - 1 Juan 4:7 💝💫",
    "«Yo soy el pan vivo.» - Juan 6:51 🍞✨",
    "«El Señor es mi sustentador.» - Salmos 54:4 💪💖",
    "«La palabra de Dios es viva.» - Hebreos 4:12 📖💫",
    "«El amor todo lo puede.» - 1 Corintios 13:7 💝✨",
    "«Yo soy el primero y el último.» - Apocalipsis 1:17 🔄🌟",
    "«El Señor es mi defensor.» - Salmos 27:1 🛡️💫",
    "«La fe obra por el amor.» - Gálatas 5:6 💝✨",
    "«Yo soy el agua viva.» - Juan 4:14 💧💖",
    "«El Señor es mi esperanza.» - Salmos 71:5 💫🌟",
    "«La palabra era Dios.» - Juan 1:1 📖✨",
    "«El amor permanece.» - 1 Corintios 13:13 💝💫",
    "«Yo soy la verdad.» - Juan 14:6 ✨💖",
    "«El Señor es mi cántico.» - Éxodo 15:2 🎵🌟",
    "«La gracia y la verdad vinieron por Cristo.» - Juan 1:17 🕊️💫",
    "«El amor es para siempre.» - 1 Corintios 13:8 💝✨",
    "«Yo soy el principio y el fin.» - Apocalipsis 22:13 🔄💖",
    "«El Señor es mi victoria.» - 1 Corintios 15:57 👑🌟",
    "«La palabra de Dios permanece.» - 1 Pedro 1:23 📖💫",
    "«Alzaré mis ojos a los montes.» - Salmos 121:1 🏔️💫",
    "«Estad quietos, y conoced que yo soy Dios.» - Salmos 46:10 🧘‍♀️✨",
    "«Enséñame, oh Jehová, tu camino.» - Salmos 27:11 👣💖",
    "«Mi copa está rebosando.» - Salmos 23:5 🏆✨",
    "«Sus misericordias son nuevas cada mañana.» - Lamentaciones 3:23 🌅💫",
    "«Él da esfuerzo al cansado.» - Isaías 40:29 💪🌟",
    "«El que habita en amor, en Dios permanece.» - 1 Juan 4:16 💝✨",
    "«Yo sé que mi Redentor vive.» - Job 19:25 ✝️💫",
    "«Mi alma espera en Jehová.» - Salmos 130:6 🙏💖",
    "«Mas a Dios gracias.» - 2 Corintios 9:15 🎁✨",
    "«Renovaos en el espíritu de vuestra mente.» - Efesios 4:23 🧠💫",
    "«Tu bondad es mejor que la vida.» - Salmos 63:3 💝🌟",
    "«Mi corazón se alegra en tu salvación.» - Salmos 13:5 😊✨",
    "«En paz me acostaré.» - Salmos 4:8 🛏️💫",
    "«Jehová cumplirá su propósito en mí.» - Salmos 138:8 🎯💖",
    "«Escudriñad las Escrituras.» - Juan 5:39 📖✨",
    "«Bienaventurados los que oyen la palabra.» - Lucas 11:28 👂💫",
    "«Mi gozo permanezca en vosotros.» - Juan 15:11 😊🌟",
    "«Cantaré a Jehová.» - Salmos 13:6 🎵💖",
    "«Dios es nuestro refugio y fortaleza.» - Salmos 46:1 🏰✨",
    "«Mi alma tiene sed de ti.» - Salmos 63:1 💧💫",
    "«Guarda tu lengua del mal.» - Salmos 34:13 🤐🌟",
    "«Andad en amor.» - Efesios 5:2 💝💖",
    "«Él conoce nuestro camino.» - Salmos 142:3 👣✨",
    "«Aguarda a Jehová.» - Salmos 27:14 ⏳💫",
    "«Tu palabra me vivifica.» - Salmos 119:50 📖🌟",
    "«Mi corazón está firme.» - Salmos 57:7 💪💖",
    "«Gracias a Dios por su don inefable.» - 2 Corintios 9:15 🎁✨",
    "«Él mismo nos capacitó.» - 2 Corintios 3:5 💫🌟",
    "«Fortaleceos en el Señor.» - Efesios 6:10 💪💖",
    "«Vuestro trabajo en el Señor no es en vano.» - 1 Corintios 15:58 ✨🌟",
    "«La gracia del Señor sea con vosotros.» - 1 Corintios 16:23 🙏💫",
    "«El Espíritu mismo intercede por nosotros.» - Romanos 8:26 🕊️💖",
    "«Dios es el que justifica.» - Romanos 8:33 ⚖️✨",
    "«Vestíos del nuevo hombre.» - Efesios 4:24 👕💫",
    "«Cristo en vosotros, la esperanza de gloria.» - Colosenses 1:27 ✝️🌟",
    "«Todo lo que respira alabe a JAH.» - Salmos 150:6 🙌💖",
    "«Creced en la gracia.» - 2 Pedro 3:18 🌱✨",
    "«Sed transformados.» - Romanos 12:2 🔄💫",
    "«El Señor es mi porción y mi copa.» - Salmos 16:5 🏆🌟",
    "«Mi alma alaba al Señor.» - Lucas 1:46 💝💖",
    "«Él da poder al débil.» - Isaías 40:29 💪✨",
    "«Tus caminos enséñame.» - Salmos 25:4 👣💫",
    "«Espera en Jehová.» - Salmos 37:34 ⏳🌟",
    "«Permaneced en mi amor.» - Juan 15:9 💝💖",
    "«Venid a mí todos.» - Mateo 11:28 🤗✨",
    "«Él nos amó primero.» - 1 Juan 4:19 💖💫",
    "«Sé fiel hasta la muerte.» - Apocalipsis 2:10 👑🌟",
    "«Alabad a Jehová.» - Salmos 117:1 🙌💖",
    "«La palabra de Dios permanece.» - 1 Pedro 1:25 📖✨",
    "«Mi paz os dejo.» - Juan 14:27 🕊️💫",
    "«Buscad primeramente el reino de Dios.» - Mateo 6:33 👑🌟",
    "«Él me guía.» - Salmos 23:3 👣💖",
    "«Mi presencia irá contigo.» - Éxodo 33:14 🌟✨",
    "«Jehová te bendiga.» - Números 6:24 🙏💫",
    "«Él da abundantemente.» - Santiago 1:5 🎁💖",
    "«Mi Dios proveerá.» - Filipenses 4:19 ✨🌟",
    "«Él es fiel.» - 1 Tesalonicenses 5:24 💫💖",
    "«La salvación es de Jehová.» - Jonás 2:9 🙏✨",
    "«Aguarda al Señor.» - Salmos 37:7 ⏳🌟",
    "«Mi corazón se goza en tu salvación.» - Salmos 13:5 💝💖",
    "«Él nos prospera.» - 3 Juan 1:2 ✨💫",
    "«Él te sustentará.» - Salmos 55:22 💪🌟",
    "«Él te guardará.» - Salmos 121:7 🛡️💖",
    "«El Señor es bueno.» - Nahúm 1:7 ✨💫",
    "«Él nos salva.» - Salmos 68:20 🙏🌟",
    "«Su misericordia es eterna.» - Salmos 136:1 💝💖",
    "«Él nos guía.» - Salmos 48:14 👣✨",
    "«El Señor es justo.» - Salmos 129:4 ⚖️💫",
    "«Él nos escucha.» - 1 Juan 5:14 👂🌟",
    "«Su amor es perfecto.» - 1 Juan 4:18 💝💖",
    "«Él nos fortalece.» - 1 Pedro 5:10 💪✨",
    "«El Señor es compasivo.» - Santiago 5:11 🤗💫",
    "«Él nos levanta.» - Salmos 145:14 🌅🌟",
    "«Su gracia es suficiente.» - 2 Corintios 12:9 🙏💖",
    "«Él nos renueva.» - Isaías 40:31 🔄✨"
];